apiVersion: v1
kind: Service
metadata:
  name: harness-python-demo
spec:
  type: NodePort
  selector:
    app: harness-python-demo
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
